function [ globR ] = assembleKGlobRsupra( g , markE0Tint , hatRdiag , hatRoffdiag , ...
    K11DG , K12DG , K21DG , K22DG )

[K, N] = size(K11DG);
globR = cell(2, 1);
globR{1} = sparse(K*N, K*N);
globR{2} = sparse(K*N, K*N);

for n = 1 : 4
    for i = 1 : N
        globR{1} = globR{1} + kron( bsxfun(@times, g.markE0TE0Tsupra{n}, (0.5 * ...
            g.NuLengthE0Tsupra(:,n,1) .* K11DG(:,i) + 0.5 * g.NuLengthE0Tsupra(:,n,2) .* ...
            K21DG(:,i)).' ) , hatRoffdiag(:,:,i,n) ) ...
            + kron( spdiags(0.5 * markE0Tint(:,n) .* g.NuLengthE0Tsupra(:,n,1) .* K11DG(:,i) ...
            + 0.5 * markE0Tint(:,n) .* g.NuLengthE0Tsupra(:,n,2) .* K21DG(:,i), 0, K, K) , ...
            hatRdiag(:,:,i,n) );
        globR{2} = globR{2} + kron( bsxfun(@times, g.markE0TE0Tsupra{n}, (0.5 * ...
            g.NuLengthE0Tsupra(:,n,1) .* K12DG(:,i) + 0.5 * g.NuLengthE0Tsupra(:,n,2) .* ...
            K22DG(:,i)).' ) , hatRoffdiag(:,:,i,n) ) ...
            + kron( spdiags(0.5 * markE0Tint(:,n) .* g.NuLengthE0Tsupra(:,n,1) .* K12DG(:,i) ...
            + 0.5 * markE0Tint(:,n) .* g.NuLengthE0Tsupra(:,n,2) .* K22DG(:,i), 0, K, K) , ...
            hatRdiag(:,:,i,n) );
    end  % for i
end  % for n

end  % function